### ISSUE TITLE
使用swagger新增接口出现一些问题

### ISSUE THREAD

**Issue by WayneLee5991** [aqiu202/RedsoftYapiUpload#10]
## 版本号
2.0.5

## 什么问题
使用swagger新增接口出现一些问题

## 如何复现此问题（描述或者截图）
1、接口名称带引号，看着太别扭了
2、在方法上右键上传，结果把整个controller类的接口都上传了
3、可以识别@ApiModelProperty注解生成入参，但是无法识别@ApiResponses注解生成响应数据
4、接口参数的实体类的属性有@NotNull注解，但是没有识别到

## idea 版本
2019.2.3

**Comment by aqiu202** [comment]
收到！
    第2个问题可能是没有选中方法名称，仅鼠标停留在方法上是无效的，不选中任何字符的情况下默认上传整个controller。
    第4个问题中的@NotNull注解的包名能提供一下吗？
感谢反馈，我会尽快确认问题，并在最新的版本中修复实际存在的问题，再次感谢！

**Comment by aqiu202** [comment]
第4个问题，该插件支持的校验注解列表如下：

    String NotNull = "javax.validation.constraints.NotNull";

    String NotBlank = "javax.validation.constraints.NotBlank";

    String NotEmpty = "javax.validation.constraints.NotEmpty";

    String Min = "javax.validation.constraints.Min";

    String Max = "javax.validation.constraints.Max";

    String Size = "javax.validation.constraints.Size";

    String Digits = "javax.validation.constraints.Digits";

    String Pattern = "javax.validation.constraints.Pattern";

    String DecimalMin = "javax.validation.constraints.DecimalMin";

    String DecimalMax = "javax.validation.constraints.DecimalMax";

    String Positive = "javax.validation.constraints.Positive";

    String PositiveOrZero = "javax.validation.constraints.PositiveOrZero";

    String Negative = "javax.validation.constraints.Negative";

    String NegativeOrZero = "javax.validation.constraints.NegativeOrZero";

    String Range = "org.hibernate.validator.constraints.Range";

    String Length = "org.hibernate.validator.constraints.Length";
