### ISSUE TITLE
备注无效

### ISSUE THREAD

**Issue by dongbiying** [aqiu202/RedsoftYapiUpload#12]
## 版本号
v2.0.5

## 什么问题
jar 增加了字段，字段注释没有问题，不知道什么原因生成后就是没有备注

![image](https://user-images.githubusercontent.com/727297/119096237-e9071f80-ba45-11eb-8f43-6ff4689e1aca.png)

![image](https://user-images.githubusercontent.com/727297/119096274-f6240e80-ba45-11eb-996b-5b1c232c0fbd.png)

## 如何复现此问题（描述或者截图）
~ 

## idea 版本
2018.3

**Comment by aqiu202** [comment]
该备注格式不符合javadoc要求，后面应该是两个*号
