### ISSUE TITLE
为啥上传的Long类型，在yapi上面显示Integer

### ISSUE THREAD

**Issue by 490727178** [aqiu202/RedsoftYapiUpload#14]
## 版本号
~ 2.0.6

## 什么问题
~为啥上传的Long类型，在yapi上面显示Integer

## 如何复现此问题（描述或者截图）
~ 
![image](https://user-images.githubusercontent.com/53554986/129125056-503d9232-ffba-41c4-9cc3-7a2156a1f2aa.png)

![image](https://user-images.githubusercontent.com/53554986/129125142-e179c97f-159e-405d-a178-15842b9b7c42.png)

## idea 版本
~ 2021.1.3

**Comment by aqiu202** [comment]
yapi表示数字只有两个类型，integer和number，integer统一表示整数，number用来泛指数字可用于表示小数，它没有java相对应的Long类型
