### ISSUE TITLE
响应参数没有注释，也没有根据配置解析为下划线

### ISSUE THREAD

**Issue by copysunday** [aqiu202/RedsoftYapiUpload#15]
## 版本号
~ 
2.0.6

## 什么问题
~
{
  "defaultSuccessCode": 1,
  "code": 1,
  "data": {
    "orderId": "String"
  },
  "message": "String"
}

## 如何复现此问题（描述或者截图）
~ 
 @JsonProperty("order_id")
    private String orderId;

## idea 版本
~

**Comment by aqiu202** [comment]
新版本2.1.0应该已修复该问题，新添加了对Jackson系列注解的支持，git已上传，Idea市场需要等待几天，谢谢反馈
