### ISSUE TITLE
responsebody或者post对象中如果有循环结构则会报内存溢出

### ISSUE THREAD

**Issue by llzzll** [aqiu202/RedsoftYapiUpload#16]
看过源代码，有一段是判断循环嵌套的，但是只能解决上级和子级相同的情况，这种方式无法解决隔级嵌套的情况。
比如A Class中有个B类型的field，然后B Class中又有个A类型的field，就会无限循环解析然后报内存溢出。

**Comment by aqiu202** [comment]
问题我已经知道了，谢谢反馈！

**Comment by aqiu202** [comment]
新版本2.1.0应该已修复该问题，git已上传，Idea市场需要等待几天，谢谢反馈
