### ISSUE TITLE
不会上传@GetMapping方法 只能上传@Postmapping

### ISSUE THREAD

**Issue by guowenzhuang** [aqiu202/RedsoftYapiUpload#2]
## 版本号
~  最新

## 什么问题
~ 不能上传@GetMapping方法 只能上传@Postmapping

## 如何复现此问题（描述或者截图）
~ 
![image](https://user-images.githubusercontent.com/40003142/83109510-1d2a5780-a0f4-11ea-8501-e9db1f7139c6.png)

## idea 版本
~idea 2020

**Comment by aqiu202** [comment]
谢谢反馈，马上修复，请您注意版本更新 谢谢

**Comment by aqiu202** [comment]
该问题已经在2.0.2版本中解决，GitHub上已经更新，可以下载后本地安装，idea仓库审核需要一两天的时间，再次感谢 ^v^
