### ISSUE TITLE
java代码中enum类型被转为object

### ISSUE THREAD

**Issue by lianglianggege1** [aqiu202/RedsoftYapiUpload#21]
## 版本号
2.1.2

## 什么问题
java代码中enum类型被转为object

## 如何复现此问题（描述或者截图）
![image](https://user-images.githubusercontent.com/36093089/184053521-745e4502-13b3-49da-9732-eec8b026c44c.png)

应该正确的
![image](https://user-images.githubusercontent.com/36093089/184053627-16176fec-ac29-4f21-bb8e-c92278b94ed6.png)

此工具显示的
object

复现过程中，发现另一个问题

显示成功，但是并没有内容
![image](https://user-images.githubusercontent.com/36093089/184055107-82902ffa-f7d1-4d23-962a-5474e94b9ed7.png)

![image](https://user-images.githubusercontent.com/36093089/184055143-5c1cd823-0317-4c59-b3d2-b990281de411.png)

## idea 版本
2020.01

**Comment by aqiu202** [comment]
问题已修改，谢谢反馈！
