### ISSUE TITLE
配置参数随便填都没有提示报错

### ISSUE THREAD

**Issue by youngledo** [aqiu202/RedsoftYapiUpload#22]
## 版本号
IDEA插件最新版

## 什么问题

参数随便填，右键上传没有任何提示，也不知道是报错了还是根本就没上传

## 如何复现此问题（描述或者截图）
如上

## idea 版本
2022.2

**Comment by aqiu202** [comment]
该问题应该已经修复了，试一下最新版本吧，谢谢反馈！
