### ISSUE TITLE
上传出现空指针

### ISSUE THREAD

**Issue by dayuange123** [aqiu202/RedsoftYapiUpload#23]
## 版本号
2.1.1+2

## 什么问题
api上传失败原因:java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "com.github.aqiu202.ideayapi.model.YApiResponse.getData()" is nu

## 如何复现此问题（描述或者截图）
~ 
![image](https://user-images.githubusercontent.com/34415174/187175216-197074de-5a5c-44e2-bb29-510bc34c9803.png)

## idea 版本
![image](https://user-images.githubusercontent.com/34415174/187175276-eb27beb1-706b-4e59-a6fa-3f321015a285.png)

**Comment by aqiu202** [comment]
我在本地使用你提供的示例并未复现该问题，可能跟YApi的版本也有关系，但是我也调整了一下代码，你试试git上最新版本2.1.1+3，看看是否还有该问题

**Comment by Inger-Chao** [comment]
我也是 这咋回事？
```JAVA
java.lang.NullPointerException
	at com.github.aqiu202.ideayapi.http.req.abs.AbstractCompoundRequestParamResolver.resolveBasic(AbstractCompoundRequestParamResolver.java:51)
```

**Comment by Inger-Chao** [comment]
> 我也是 这咋回事？
> 
> ```java
> java.lang.NullPointerException
> 	at com.github.aqiu202.ideayapi.http.req.abs.AbstractCompoundRequestParamResolver.resolveBasic(AbstractCompoundRequestParamResolver.java:51)
> ```

问题已解决：PostMapping 的入参列表必须添加 @RequestParam 或者 @RequestBody
