### ISSUE TITLE
接口返回对象中如果有多个属性使用同一个类，在yapi上显示将会只有一个属性被正常解析

### ISSUE THREAD

**Issue by mml885522** [aqiu202/RedsoftYapiUpload#25]
## 版本号
yapi版本1.8.5

## 什么问题
~

## 如何复现此问题（描述或者截图）
~ 

## idea 版本
2020.3

**Comment by aqiu202** [comment]
这是因为防止参数类型循环嵌套，解析时会出现内存溢出，所以特意做了类型的解析限制，不重复解析同一类型，考虑下一版本优化该限制策略--设置解析的最大嵌套层数，你有没有其他好的想法？

**Comment by aqiu202** [comment]
该问题已经在v2.2.1版本完善
