### ISSUE TITLE
结果类里的泛型属性没有识别

### ISSUE THREAD

**Issue by guangshuowang** [aqiu202/RedsoftYapiUpload#31]
## 版本号
~ 
2.2.1
## 什么问题
~通用的结果包装类中的泛型对象，没有识别属性

## 如何复现此问题（描述或者截图）
~ 我的successResult是下面自定义对象类型，包含了自身属性，这里只识别成了object
![image](https://github.com/aqiu202/RedsoftYapiUpload/assets/17266306/31bc7d29-d431-40d2-9dba-b86b48e00c67)
![image](https://github.com/aqiu202/RedsoftYapiUpload/assets/17266306/9325b9d4-3fd5-47b0-8f7c-b583c94a2fb7)

## idea 版本
~2022.3.1

**Comment by aqiu202** [comment]
泛型要在类型定义时声明
