### ISSUE TITLE
超出最大解析层数:5，不再展示详细字段信息

### ISSUE THREAD

**Issue by niyueyeee** [aqiu202/RedsoftYapiUpload#33]
## 版本号
~ 

## 什么问题
~超出最大解析层数:5，不再展示详细字段信息

## 如何复现此问题（描述或者截图）
~ 
![image](https://github.com/aqiu202/RedsoftYapiUpload/assets/35424140/3a7abcc5-ada8-4fd2-98b8-052cb4742159)

## idea 版本
~

**Comment by aqiu202** [comment]
对于存在循环依赖的情况，为了防止无限制的数据解析而导致内存溢出，插件设置了最大的解析层数，最新版本中最大的解析层数为8层

**Comment by niyueyeee** [comment]
在用版本号是2.2.1  最新版在哪里下载

aqiu ***@***.***> 于2024年1月25日周四 11:24写道：

**Comment by niyueyeee** [comment]
插件最大的解析层数  能否可以放开给使用方取配置

**Comment by aqiu202** [comment]
新的版本2.2.2，明天左右应该在idea上就会看见了
