### ISSUE TITLE
@status注解不生效

### ISSUE THREAD

**Issue by luckyQing** [aqiu202/RedsoftYapiUpload#4]
## 版本号
~ 2.0.2

## 什么问题
~ @status (done、undone) 接口状态注解不支持

## 如何复现此问题（描述或者截图）
~ 

## idea 版本
~ ideaIC-2020.1.2.win

**Comment by aqiu202** [comment]
谢谢反馈，2.0.3版本已经修复该问题！该版本两三天之后就可以在idea仓库中看到了。
