### ISSUE TITLE
使用RequestParam没有根据value生成

### ISSUE THREAD

**Issue by dartick** [aqiu202/RedsoftYapiUpload#5]
## 版本号
~ 2.0.4

## 什么问题
~使用RequestParam没有根据value生成

## 如何复现此问题（描述或者截图）
~ @RequestParam(value = "user_id") Long userId

## idea 版本
~2020.01

## 希望新增功能
~tag设置
~多级分类
~枚举值

**Comment by aqiu202** [comment]
谢谢反馈，马上解决！多级分类和json-schema的枚举语法YApi暂不支持（建议使用参数注释暂时替代枚举的用法），谢谢支持😊

**Comment by aqiu202** [comment]
2.0.4_bugfix版本已经修复该BUG！
