### ISSUE TITLE
选择SnakeCase，不会作用到RequestBody 对象内部的属性

### ISSUE THREAD

**Issue by wxw1111** [aqiu202/RedsoftYapiUpload#6]
## 版本号
2.0.4_bugfix_1

## 什么问题
选择SnakeCase，不会作用到RequestBody 对象内部的属性

## 如何复现此问题（描述或者截图）
现在是：
{
  "accountType":"String", // 账号类型 ALIPAY：支付宝，WEIXINPAY：微信，BANKTRANSFER：银行转账,
  ...
}
期望是：
{
  "account_type":"String", // 账号类型 ALIPAY：支付宝，WEIXINPAY：微信，BANKTRANSFER：银行转账,
  ...
}

## idea 版本
2020.2

**Comment by aqiu202** [comment]
谢谢反馈，马上完善！😁

**Comment by aqiu202** [comment]
GitHub上最新的版本已经修复该问题，已上传idea官方插件库，正在审核中！😊

**Comment by wxw1111** [comment]
> GitHub上最新的版本已经修复该问题，已上传idea官方插件库，正在审核中！


谢谢！加@RequestBody后会生效，但是不加SnakeCase不会生效
例如：
```
void applyShip(@PathVariable("service_sn") String serviceSn, @ApiIgnore Integer courierCompanyId, @ApiIgnore String courierNumber, @ApiIgnore Long shipTime)
```
Yapi显示如下：
![image](https://user-images.githubusercontent.com/47956634/90206778-1bc91b00-de17-11ea-8f5b-65127fd2e8fc.png)

**Comment by aqiu202** [comment]
> > GitHub上最新的版本已经修复该问题，已上传idea官方插件库，正在审核中！
> 
> 谢谢！加@requestbody后会生效，但是不加SnakeCase不会生效
> 例如：
> 
> ```
> void applyShip(@PathVariable("service_sn") String serviceSn, @ApiIgnore Integer courierCompanyId, @ApiIgnore String courierNumber, @ApiIgnore Long shipTime)
> ```
> 
> Yapi显示如下：
> ![image](https://user-images.githubusercontent.com/47956634/90206778-1bc91b00-de17-11ea-8f5b-65127fd2e8fc.png)

SpringMVC中加@RequestBody注解的参数绑定是由jackson解析的，其他的参数绑定不会经过jackson的，建议使用@RequestParam注解去重命名字段例如：
```java
void test(@RequestParam("service_sn") String serviceSn);
```

**Comment by wxw1111** [comment]
> > > GitHub上最新的版本已经修复该问题，已上传idea官方插件库，正在审核中！
> > 
> > 
> > 谢谢！加@requestbody后会生效，但是不加SnakeCase不会生效
> > 例如：
> > ```
> > void applyShip(@PathVariable("service_sn") String serviceSn, @ApiIgnore Integer courierCompanyId, @ApiIgnore String courierNumber, @ApiIgnore Long shipTime)
> > ```
> > 
> > 
> > Yapi显示如下：
> > ![image](https://user-images.githubusercontent.com/47956634/90206778-1bc91b00-de17-11ea-8f5b-65127fd2e8fc.png)
> 
> SpringMVC中加@requestbody注解的参数绑定是由jackson解析的，其他的参数绑定不会经过jackson的，建议使用@RequestParam注解去重命名字段例如：
> 
> ```java
> void test(@RequestParam("service_sn") String serviceSn);
> ```

OK
