### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by herongyun** [aqiu202/RedsoftYapiUpload#7]
## 版本号
~ 2.0.4-fixbug_2

## 什么问题
~低版本的spring-web 通过    @RequestMapping(value = "/all", method = RequestMethod.GET)定义接口，获取基本信息时报错，Cannot read property 'request_body' of undefined

## 如何复现此问题（描述或者截图）
~ 低版本的spring-web  只有@RequestMapping  没有    @GetMapping

## idea 版本
~ 2019.1.3

**Comment by aqiu202** [comment]
已知晓，谢谢反馈！😊

**Comment by aqiu202** [comment]
该问题在2.0.5版本已经修复😄
