### ISSUE TITLE
返回对象中内部类无法正常解析成yapi中的json格式

### ISSUE THREAD

**Issue by JoyceeLin** [aqiu202/RedsoftYapiUpload#8]
## 版本号
~ 
2.0.5
## 什么问题
~
返回对象中有内部类的话无法正常解析成yapi中的json格式
## 如何复现此问题（描述或者截图）
~ 
返回对象中参数为当前类的内部类
## idea 版本
~
2018.1.4

**Comment by aqiu202** [comment]
对象的属性才会被序列化解析，内部类没有实例属性的话是不会被序列化解析的
