### ISSUE TITLE
怎么过滤实体对象字段？

### ISSUE THREAD

**Issue by Dear-Tao** [aqiu202/RedsoftYapiUpload#9]
## 版本号
~ 2.0.5

## 什么问题
~  请问 实体中有些字段不需要展示 怎么过滤掉

## 如何复现此问题（描述或者截图）
~ 

## idea 版本
~ 2019.3.2

**Comment by aqiu202** [comment]
该功能暂未实现，请随时注意版本更新

**Comment by yejunxi** [comment]
> 该功能暂未实现，请随时注意版本更新

两年啦，这个快更新啦~

**Comment by aqiu202** [comment]
新版本2.1.0可以通过@deprecated注释或者Jackson注解（@JsonIgnore、@JsonIgnoreProperties和@JsonIncludeProperties）对字段进行过滤，git已上传，Idea市场需要等待几天，谢谢您长期的关注
